import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar }  from "@/components/global/Navbar";
import NavbarWrapper from "@/components/global/NavbarWrapper";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarWrapper />
        {children}
        <Toaster 
          position="bottom-right" 
          toastOptions={{
            style: { 
              background: 'white', 
              color: 'black', 
              border: '1px solid #e2e8f0' 
            },
            classNames: {
              title: 'text-black font-medium',
              description: 'text-zinc-900 font-normal', // Darker gray for readability
              toast: 'rounded-xl shadow-lg p-4',
            }
          }}
        />
      </body>
    </html>
  );
}
